### ISSUE TITLE
TooManyRequests exception

### ISSUE THREAD

**Issue by zrzka** [purposefly/scripta#1]
```
Deploying API Gateway to stage: v1
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.5/site-packages/scripta/main.py", line 24, in invoke
    function(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/scripta/aws/apigateway.py", line 76, in create_deployment
    description=xargs.description
  File "/home/travis/miniconda/lib/python3.5/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/miniconda/lib/python3.5/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (TooManyRequestsException) when calling the CreateDeployment operation: Too Many Requests
```

It happens when we're adding lot of permissions, deploying new api gateway stage, ... boto3 should return number of seconds we should wait and then retry. I was forced to add `sleep ..` into my deployment scripts as a quick workaround.

**Comment by coells** [comment]
can not reproduce, added HTTP error response logging to catch future problems

**Comment by zrzka** [comment]
https://travis-ci.com/purposefly/apps/builds/30125145

```
Deploying API Gateway to stage: v1
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.5/site-packages/scripta/main.py", line 25, in invoke
    function(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/scripta/aws/apigateway.py", line 76, in create_deployment
    description=xargs.description
  File "/home/travis/miniconda/lib/python3.5/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/miniconda/lib/python3.5/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (TooManyRequestsException) when calling the CreateDeployment operation: Too Many Requests
{'Error': {'Code': 'TooManyRequestsException', 'Message': 'Too Many Requests'},
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '57',
                                      'content-type': 'application/json',
                                      'date': 'Fri, 19 Aug 2016 12:05:06 GMT',
                                      'x-amzn-errortype': 'TooManyRequestsException',
                                      'x-amzn-requestid': '2b58ac5d-6605-11e6-b12c-2508f8314447'},
                      'HTTPStatusCode': 429,
                      'RequestId': '2b58ac5d-6605-11e6-b12c-2508f8314447'}}
```

**Comment by zrzka** [comment]
There's no backoff time in response. So, go ahead with backoff ...
- 1, 2, 4, 8, 16, 32, 64, ... seconds

... and bail out if the back off is longer than 5 minutes. In our particular case, it's enough to wait for ~5s. We can probably bail out if 64 seconds are not enough.

**Comment by coells** [comment]
dat LOL, I'll implement back-off strategy today later

**Comment by coells** [comment]
implemented 1,4,16,64 backoff times
